create table if not exists public.ocr_results (
  id bigint generated by default as identity primary key,
  file_name text not null,
  file_type text not null,
  extracted_text text not null,
  storage_path text,
  storage_url text,
  created_at timestamptz not null default now()
);

alter table public.ocr_results enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'ocr_results'
      and policyname = 'service_role_full_access_ocr_results'
  ) then
    create policy service_role_full_access_ocr_results
      on public.ocr_results
      for all
      to service_role
      using (true)
      with check (true);
  end if;
end $$;
